# -*- coding: utf-8 -*-
"""PyV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lbF6TLL47bpr_ir-3TFnY8XWqzLP9eWk
"""

#!/usr/bin/python3
# -*- coding: utf-8 -*-
"""
pyv.py

VS Code-friendly version of the Colab PyV notebook.

Notes:
- Uses `GROQ_API_KEY` from the environment if present.
- Supports `--mode dry-run` (generate audio assets only) for quick local testing
  without Manim/LaTeX/ffmpeg.
- Use `--mode render` to run Manim (requires Manim, LaTeX, ffmpeg installed).
"""

import os
import json
import random
import argparse
import logging
import sys
from pathlib import Path

# Optional dependencies (graceful fallbacks)
MANIM_AVAILABLE = True
try:
    from manim import *
except Exception:
    MANIM_AVAILABLE = False

GROQ_AVAILABLE = True
try:
    from groq import Groq
except Exception:
    GROQ_AVAILABLE = False

GTTS_AVAILABLE = True
try:
    from gtts import gTTS
except Exception:
    GTTS_AVAILABLE = False

MOVIEPY_AVAILABLE = True
try:
    from moviepy.editor import AudioFileClip
except Exception:
    MOVIEPY_AVAILABLE = False

logging.basicConfig(level=logging.INFO, format='[%(levelname)s] %(message)s')

# Basic Manim config (if available)
if MANIM_AVAILABLE:
    try:
        config.background_color = "#0a0a0a"
        config.pixel_height = 1080
        config.pixel_width = 1920
        config.frame_rate = 60
    except Exception:
        pass

# Read GROQ API key from environment (safer than hard-coding)
# Use the variable name `GROQ_API_KEY` — set this in your environment.
GROQ_API_KEY = os.environ.get("GROQ_API_KEY")

def sample_curriculum(topic):
    """Return a simple 6-step sample curriculum (fallback)."""
    steps = []
    for i in range(6):
        steps.append({
            "math": f"\\mathrm{{Sample\\ Formula\\ {i+1}}}",
            "explanation": f"Step {i+1}: Key idea for {topic}.",
            "speech": f"This is a sample narration for step {i+1} of {topic}. Explain the concept clearly and slowly."
        })
    return steps

def get_cbse_curriculum(topic, timeout=30):
    """Call Groq to get a curriculum, or fall back to a sample if unavailable."""
    if GROQ_API_KEY and GROQ_AVAILABLE:
        try:
            client = Groq(api_key=GROQ_API_KEY)
            prompt = f"""
            You are a PhD Math Teacher. Create a 6-step curriculum for: {topic}.
            Return JSON: {{'steps': [{{'math': 'LaTeX', 'explanation': 'Header', 'speech': 'Detailed teaching narrative'}}]}}
            """
            completion = client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[{"role": "user", "content": prompt}],
                response_format={"type": "json_object"},
                timeout=timeout,
            )
            return json.loads(completion.choices[0].message.content)["steps"]
        except Exception as e:
            logging.warning("Groq request failed (%s). Falling back to sample curriculum.", e)
            return sample_curriculum(topic)
    else:
        if not GROQ_AVAILABLE:
            logging.info("Groq package not installed; using sample curriculum.")
        elif not GROQ_API_KEY:
            logging.info("GROQ_API_KEY not set; using sample curriculum.")
        return sample_curriculum(topic)

def generate_audio_for_steps(steps, output_dir):
    """Generate TTS audio files for each step (or write text fallbacks).

    Returns a list of durations (seconds) or None where unavailable.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    durations = []
    for i, step in enumerate(steps):
        audio_path = output_dir / f"step_{i}.mp3"
        if GTTS_AVAILABLE:
            try:
                gTTS(text=step["speech"], lang="en").save(str(audio_path))
                logging.info("Saved audio: %s", audio_path)
            except Exception as e:
                logging.warning("gTTS save failed (%s); writing text fallback.", e)
                audio_path.write_text(step["speech"], encoding="utf-8")
        else:
            logging.info("gTTS not installed; writing text fallback for step %d.", i)
            audio_path.write_text(step["speech"], encoding="utf-8")

        dur = None
        if MOVIEPY_AVAILABLE and audio_path.exists() and audio_path.suffix == ".mp3":
            try:
                dur = AudioFileClip(str(audio_path)).duration
            except Exception:
                dur = None
        durations.append(dur)
    return durations

# Manim scene (only defined when Manim is available)
if MANIM_AVAILABLE:
    class MasterclassScene(MovingCameraScene):
        def construct(self):
            steps = getattr(self, "steps", [])
            output_dir = getattr(self, "output_dir", ".")

            particles = VGroup(*[
                Dot(radius=0.02, color=BLUE, fill_opacity=0.2).move_to([random.uniform(-7,7), random.uniform(-4,4), 0])
                for _ in range(30)
            ])
            self.add(particles)
            for p in particles:
                p.add_updater(lambda m, dt: m.shift(UP * 0.1 * dt if random.random() > 0.5 else DOWN * 0.1 * dt))

            header = VGroup(
                Text("PREMIUM CBSE MASTERCLASS", font_size=20, color=GOLD, weight=BOLD),
                Text(getattr(self, "topic", ""), font_size=34, color=WHITE)
            ).arrange(DOWN, buff=0.1).to_edge(UP, buff=0.4)
            line = Line(LEFT*7, RIGHT*7, color=BLUE, stroke_width=1).next_to(header, DOWN, buff=0.2)
            self.add(header, line)

            for i, step in enumerate(steps):
                audio_file = os.path.join(output_dir, f"step_{i}.mp3")
                audio_dur = None
                if os.path.exists(audio_file) and MOVIEPY_AVAILABLE:
                    try:
                        audio_dur = AudioFileClip(audio_file).duration
                    except Exception:
                        audio_dur = None

                math_mob = MathTex(step.get('math', '').replace("$", ""), color="#00FFFF").scale(1.4)
                glow = math_mob.copy().set_stroke(width=8, opacity=0.3).set_color("#00FFFF")
                formula = VGroup(glow, math_mob)

                explanation = Text(step.get('explanation', ''), font_size=38, color=YELLOW).next_to(formula, UP, buff=1.2)
                caption = Text(step.get('speech', ''), font_size=22, color=WHITE, line_spacing=1.5).to_edge(DOWN, buff=0.8)
                try:
                    if caption.width > 12:
                        caption.scale(12/caption.width)
                except Exception:
                    pass

                self.add_sound(audio_file)

                pointer = Circle(radius=0.2, color=GOLD, stroke_width=2).move_to(ORIGIN)
                self.play(Create(pointer), pointer.animate.scale(1.5).set_stroke(opacity=0), run_time=0.8)

                self.play(
                    Write(math_mob, run_time=2),
                    FadeIn(glow, run_time=3),
                    FadeIn(explanation, shift=DOWN),
                    FadeIn(caption),
                    self.camera.frame.animate.scale(0.85).move_to(formula),
                    run_time=2
                )

                wait_time = max(1, audio_dur - 2) if audio_dur else 2
                self.wait(wait_time)

                self.play(
                    FadeOut(formula),
                    FadeOut(explanation),
                    FadeOut(caption),
                    self.camera.frame.animate.scale(1.17).move_to(ORIGIN)
                )
else:
    MasterclassScene = None

def produce_video(topic, output_dir="outputs", mode="dry-run"):
    steps = get_cbse_curriculum(topic)
    durations = generate_audio_for_steps(steps, output_dir)
    logging.info("Generated %d audio assets.", len(durations))

    if mode == "dry-run":
        logging.info("Dry-run complete. Audio files saved under: %s", output_dir)
        for i, d in enumerate(durations):
            logging.info("step_%d.mp3 duration: %s", i, d)
        return

    if mode == "render":
        if not MANIM_AVAILABLE:
            raise RuntimeError("Manim not available. Install Manim + LaTeX + ffmpeg to render.")
        MasterclassScene.steps = steps
        MasterclassScene.topic = topic
        MasterclassScene.output_dir = output_dir
        scene = MasterclassScene()
        scene.render()
        logging.info("Render complete. Check Manim's media directory for the final video.")

def main():
    parser = argparse.ArgumentParser(description="PyV — generate educational videos (VS Code friendly)")
    parser.add_argument("--topic", "-t", default="Fundamental Theorem of Arithmetic", help="Lesson topic")
    parser.add_argument("--output", "-o", default="outputs", help="Output folder for audio/video")
    parser.add_argument("--mode", "-m", choices=["dry-run", "render"], default="dry-run", help="dry-run: generate assets only; render: run Manim to produce video")
    args = parser.parse_args()

    out = Path(args.output)
    out.mkdir(parents=True, exist_ok=True)

    try:
        produce_video(args.topic, output_dir=str(out), mode=args.mode)
    except Exception as e:
        logging.exception("Failed to produce video: %s", e)
        sys.exit(1)

    logging.info("Done. Output directory: %s", out.resolve())

if __name__ == "__main__":
    main()
