# -*- coding: utf-8 -*-
"""PyV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lbF6TLL47bpr_ir-3TFnY8XWqzLP9eWk
"""

#!/usr/bin/python3
# -*- coding: utf-8 -*-
"""
pyv.py

VS Code-friendly version of the Colab PyV notebook.

Notes:
- Uses `GROQ_API_KEY` from the environment if present.
- Supports `--mode dry-run` (generate audio assets only) for quick local testing
  without Manim/LaTeX/ffmpeg.
- Use `--mode render` to run Manim (requires Manim, LaTeX, ffmpeg installed).
"""

import os
import json
import random
import argparse
import logging
import sys
from pathlib import Path

# Optional dependencies (graceful fallbacks)
MANIM_AVAILABLE = True
try:
    from manim import *
except Exception:
    MANIM_AVAILABLE = False

GROQ_AVAILABLE = True
try:
    from groq import Groq
except Exception:
    GROQ_AVAILABLE = False

GTTS_AVAILABLE = True
try:
    from gtts import gTTS
except Exception:
    GTTS_AVAILABLE = False

MOVIEPY_AVAILABLE = True
try:
    from moviepy.editor import AudioFileClip
except Exception:
    MOVIEPY_AVAILABLE = False

PYDUB_AVAILABLE = True
try:
    from pydub import AudioSegment
except Exception:
    PYDUB_AVAILABLE = False

logging.basicConfig(level=logging.INFO, format='[%(levelname)s] %(message)s')

# Basic Manim config (if available)
if MANIM_AVAILABLE:
    try:
        config.background_color = "#0a0a0a"
        config.pixel_height = 1080
        config.pixel_width = 1920
        config.frame_rate = 60
    except Exception:
        pass

# GROQ API key should come from environment for security.
# To enable live Groq calls set `ENABLE_GROQ=1` and provide `GROQ_API_KEY` in your environment.
GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")
USE_GROQ = os.environ.get("ENABLE_GROQ", "0") == "1"

def sample_curriculum(topic):
    """Return a simple 6-step sample curriculum (fallback)."""
    steps = []
    for i in range(6):
        steps.append({
            "math": f"\\mathrm{{Sample\\ Formula\\ {i+1}}}",
            "explanation": f"Step {i+1}: Key idea for {topic}.",
            "speech": f"This is a sample narration for step {i+1} of {topic}. Explain the concept clearly and slowly."
        })
    return steps

def get_cbse_curriculum(topic, timeout=30):
    """Call Groq to get a curriculum, or fall back to a sample if unavailable."""
    if GROQ_API_KEY and GROQ_AVAILABLE and USE_GROQ:
        try:
            client = Groq(api_key=GROQ_API_KEY)
            prompt = f"""
            You are a PhD Math Teacher. Create a 6-step curriculum for: {topic}.
            Return JSON: {{'steps': [{{'math': 'LaTeX', 'explanation': 'Header', 'speech': 'Detailed teaching narrative'}}]}}
            """
            completion = client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[{"role": "user", "content": prompt}],
                response_format={"type": "json_object"},
                timeout=timeout,
            )
            return json.loads(completion.choices[0].message.content)["steps"]
        except Exception as e:
            logging.warning("Groq request failed (%s). Falling back to sample curriculum.", e)
            return sample_curriculum(topic)
    else:
        if not GROQ_AVAILABLE:
            logging.info("Groq package not installed; using sample curriculum.")
        elif not GROQ_API_KEY:
            logging.info("GROQ_API_KEY not set; using sample curriculum.")
        elif not USE_GROQ:
            logging.info("ENABLE_GROQ not set; using sample curriculum.")
        return sample_curriculum(topic)


def get_cbse_script(topic, timeout=60):
    """Call Groq with the full CBSE/NCERT teaching-video prompt and return the raw script text.

    Returns the model's text output on success, or None if Groq is unavailable/disabled or an error occurs.
    """
    if not (GROQ_API_KEY and GROQ_AVAILABLE and USE_GROQ):
        if not GROQ_AVAILABLE:
            logging.info("Groq package not installed; cannot request full script.")
        elif not GROQ_API_KEY:
            logging.info("GROQ_API_KEY not set; cannot request full script.")
        elif not USE_GROQ:
            logging.info("ENABLE_GROQ not set; Groq disabled by environment.")
        return None

    try:
        client = Groq(api_key=GROQ_API_KEY)
        prompt_template = '''You are an expert CBSE teacher and instructional designer. Generate a complete teaching video script strictly aligned with the Central Board of Secondary Education (CBSE) syllabus and NCERT textbooks for this topic: [TOPIC]

Follow ALL rules below without exception:

1. Curriculum Accuracy (Non-negotiable)

* Strictly follow CBSE syllabus and NCERT content.
* Do NOT include any out-of-syllabus topics.
* Use exact CBSE/NCERT terminology.
* Ensure all explanations match exam expectations.

2. Structured Explanation Format
   Start with clear learning objectives.

Then follow this sequence:

* Concept Introduction
* Step-by-step Explanation
* Real-life Example
* Practice Question
* Summary

3. Conceptual Clarity

* Focus on understanding, not memorization.
* Explain WHY each concept works, not just WHAT it is.
* Use analogies, simple explanations, and diagrams (describe visuals for video).
* Break down complex problems step-by-step.

4. Visual Instructions (for video generation)

* Suggest clean, minimal visuals for each step.
* Highlight key formulas and important points.
* Prefer board-style or simple diagram explanations.
* Avoid clutter or unnecessary animations.

5. Voice & Language Style

* Use simple, clear Indian English.
* Gradually introduce technical terms after basic explanation.
* Maintain natural teaching tone (not robotic).
* Optionally include simple Hindi support if helpful.

6. Exam-Oriented Content

* Include at least 1 previous year or exam-style question.
* Provide step-by-step solution.
* Highlight important exam tips.
* Mention common mistakes students make.

7. Video Length Optimization

* Keep script suitable for 5–10 minutes per concept.
* If topic is long, logically split into parts.

8. Interactive Elements

* Insert “Pause and Try” questions.
* Add quick quizzes or checkpoints.

9. Accessibility

* Ensure content is mobile-friendly.
* Include subtitle-friendly sentences (short and clear).

10. Strict Quality Control

* Do NOT hallucinate facts.
* Do NOT skip steps in explanations.
* Do NOT use generic or foreign curriculum style.

Output Format:

* Title
* Learning Objectives
* Full Script (with narration + visual instructions)
* Practice Questions
* Summary
* Key Exam Tips
* Common Mistakes

When you generate the script, follow the Output Format exactly and keep subtitles concise for mobile.

Return the complete script following the Output Format exactly. Do not add any extra preface, notes, or meta commentary. End the response with a brief "Estimated total duration: mm:ss" line.
'''

        prompt = prompt_template.replace('[TOPIC]', topic)

        completion = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            timeout=timeout,
        )

        # Return the raw text response; caller can parse as needed
        return completion.choices[0].message.content
    except Exception as e:
        logging.warning("Groq script request failed (%s).", e)
        return None

def generate_audio_for_steps(steps, output_dir):
    """Generate TTS audio files for each step (or write text fallbacks).

    Returns a tuple: (durations_list, combined_audio_path_or_None).
    - durations_list: list of durations (seconds) or None where unavailable.
    - combined_audio_path_or_None: path to a single concatenated WAV file when created, otherwise None.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    durations = []
    audio_files = []
    for i, step in enumerate(steps):
        mp3_path = output_dir / f"step_{i}.mp3"
        wav_path = output_dir / f"step_{i}.wav"
        use_tts = GTTS_AVAILABLE and os.environ.get("DISABLE_TTS", "0") != "1"
        if use_tts:
            try:
                gTTS(text=step["speech"], lang="en").save(str(mp3_path))
                logging.info("Saved audio (mp3): %s", mp3_path)
            except Exception as e:
                logging.warning("gTTS save failed (%s); writing text fallback.", e)
                mp3_path.write_text(step["speech"], encoding="utf-8")
        else:
            logging.info("gTTS disabled or not installed; writing text fallback for step %d.", i)
            mp3_path.write_text(step["speech"], encoding="utf-8")

        # Convert to WAV for more reliable timing in Manim
        dur = None
        try:
            if PYDUB_AVAILABLE and mp3_path.exists():
                seg = AudioSegment.from_file(str(mp3_path))
                seg.export(str(wav_path), format="wav")
                dur = len(seg) / 1000.0
                logging.info("Converted to wav: %s (%.2fs)", wav_path, dur)
            elif MOVIEPY_AVAILABLE and mp3_path.exists():
                dur = AudioFileClip(str(mp3_path)).duration
                # fallback: use mp3 as audio file
                wav_path = mp3_path
            else:
                wav_path = mp3_path
        except Exception as e:
            logging.warning("Audio conversion/duration failed (%s). Trying fallback placeholder.", e)
            # Try moviepy duration first
            try:
                if MOVIEPY_AVAILABLE and mp3_path.exists():
                    dur = AudioFileClip(str(mp3_path)).duration
            except Exception:
                dur = None

            # If still no duration, create a short silent placeholder WAV so rendering can proceed
            if dur is None and PYDUB_AVAILABLE:
                try:
                    silent_ms = 2000
                    silent_seg = AudioSegment.silent(duration=silent_ms)
                    silent_seg.export(str(wav_path), format="wav")
                    dur = silent_ms / 1000.0
                    logging.info("Wrote placeholder silent wav: %s (%.2fs)", wav_path, dur)
                except Exception as e2:
                    logging.warning("Failed to write silent placeholder (%s).", e2)

        # Attach duration and chosen audio file back into the step for scene usage
        try:
            step["audio_dur"] = dur
            chosen = str(wav_path) if wav_path.exists() else str(mp3_path)
            step["audio_file"] = chosen
            audio_files.append(chosen)
        except Exception:
            pass

        durations.append(dur)

    # Try to create a combined audio file (concatenate in order) to avoid overlap
    combined_path = None
    try:
        if PYDUB_AVAILABLE and audio_files:
            segments = []
            for p in audio_files:
                try:
                    seg = AudioSegment.from_file(p)
                    segments.append(seg)
                except Exception:
                    # if any file fails to load, abort combined creation
                    segments = []
                    break

            if segments:
                combined = AudioSegment.silent(duration=0)
                gap = 200  # ms small gap between segments
                for seg in segments:
                    combined += seg + AudioSegment.silent(duration=gap)

                combined_path = output_dir / "combined_steps.wav"
                combined.export(str(combined_path), format="wav")
                logging.info("Exported combined audio: %s", combined_path)

                # compute per-step start times and update steps
                current = 0.0
                for idx, seg in enumerate(segments):
                    steps[idx]["audio_start"] = current
                    seg_dur = len(seg) / 1000.0
                    steps[idx]["audio_dur"] = seg_dur
                    current += seg_dur + (gap / 1000.0)
    except Exception as e:
        logging.warning("Failed to create combined audio (%s). Continuing without it.", e)

    return durations, str(combined_path) if combined_path else None

# Manim scene (only defined when Manim is available)
if MANIM_AVAILABLE:
    class MasterclassScene(MovingCameraScene):
        def construct(self):
            steps = getattr(self, "steps", [])
            output_dir = getattr(self, "output_dir", ".")

            particles = VGroup(*[
                Dot(radius=0.02, color=BLUE, fill_opacity=0.2).move_to([random.uniform(-7,7), random.uniform(-4,4), 0])
                for _ in range(30)
            ])
            self.add(particles)
            for p in particles:
                p.add_updater(lambda m, dt: m.shift(UP * 0.1 * dt if random.random() > 0.5 else DOWN * 0.1 * dt))

            header = VGroup(
                Text("PREMIUM CBSE MASTERCLASS", font_size=20, color=GOLD, weight=BOLD),
                Text(getattr(self, "topic", ""), font_size=34, color=WHITE)
            ).arrange(DOWN, buff=0.1).to_edge(UP, buff=0.4)
            line = Line(LEFT*7, RIGHT*7, color=BLUE, stroke_width=1).next_to(header, DOWN, buff=0.2)
            self.add(header, line)

            # If a combined audio file was produced, play it once and schedule animations to its timestamps
            combined_audio = getattr(self, "combined_audio", None)
            current_time = 0.0
            if combined_audio and os.path.exists(combined_audio):
                self.add_sound(combined_audio)

            for i, step in enumerate(steps):
                audio_dir = getattr(self, "temp_dir", output_dir)

                # Prepare visual elements
                math_mob = MathTex(step.get('math', '').replace("$", ""), color="#00FFFF").scale(1.0)
                glow = math_mob.copy().set_stroke(width=8, opacity=0.3).set_color("#00FFFF")
                formula = VGroup(glow, math_mob)

                # Ensure formula fits in frame
                try:
                    max_width = 12
                    if formula.width > max_width:
                        formula.scale(max_width / formula.width)
                except Exception:
                    pass

                explanation = Text(step.get('explanation', ''), font_size=38, color=YELLOW).next_to(formula, UP, buff=1.2)
                caption = Text(step.get('speech', ''), font_size=22, color=WHITE, line_spacing=1.5).to_edge(DOWN, buff=0.8)
                try:
                    if caption.width > 12:
                        caption.scale(12/caption.width)
                except Exception:
                    pass

                # Per-step audio metadata
                audio_start = step.get("audio_start")
                audio_dur = step.get("audio_dur") if isinstance(step, dict) else None

                if combined_audio and audio_start is not None:
                    # fast-forward scene time to the audio start
                    delta = audio_start - current_time
                    if delta > 0:
                        self.wait(delta)
                        current_time += delta
                else:
                    # Fallback: play per-step audio now
                    audio_file = step.get("audio_file")
                    if not audio_file:
                        wav_path = os.path.join(audio_dir, f"step_{i}.wav")
                        mp3_path = os.path.join(audio_dir, f"step_{i}.mp3")
                        audio_file = wav_path if os.path.exists(wav_path) else mp3_path
                    self.add_sound(audio_file)

                # Animations
                pointer = Circle(radius=0.2, color=GOLD, stroke_width=2).move_to(ORIGIN)
                pointer_rt = 0.8
                main_rt = 2
                self.play(Create(pointer), pointer.animate.scale(1.5).set_stroke(opacity=0), run_time=pointer_rt)

                self.play(
                    Write(math_mob, run_time=main_rt),
                    FadeIn(glow, run_time=main_rt + 1),
                    FadeIn(explanation, shift=DOWN),
                    FadeIn(caption),
                    self.camera.frame.animate.scale(0.85).move_to(formula),
                    run_time=main_rt
                )

                anim_time = pointer_rt + main_rt
                current_time += anim_time

                if combined_audio and audio_start is not None:
                    # wait until the audio segment for this step finishes
                    end_time = audio_start + (audio_dur or 0)
                    wait_end = end_time - current_time
                    if wait_end > 0:
                        self.wait(wait_end)
                        current_time += wait_end
                else:
                    # fallback per-step wait based on detected duration
                    if audio_dur and audio_dur > anim_time:
                        wait_time = audio_dur - anim_time
                    else:
                        wait_time = 0.5
                    self.wait(wait_time)
                    current_time += wait_time

                self.play(
                    FadeOut(formula),
                    FadeOut(explanation),
                    FadeOut(caption),
                    self.camera.frame.animate.scale(1.17).move_to(ORIGIN)
                )
else:
    MasterclassScene = None

def produce_video(topic, output_dir="outputs", mode="dry-run", temp_dir=None):
    steps = get_cbse_curriculum(topic)
    # write audio assets into the temporary directory first
    audio_dir = temp_dir if temp_dir else output_dir
    durations, combined_audio = generate_audio_for_steps(steps, audio_dir)
    logging.info("Generated %d audio assets.", len(durations))

    if mode == "dry-run":
        logging.info("Dry-run complete. Audio files saved under: %s", output_dir)
        for i, d in enumerate(durations):
            logging.info("step_%d.mp3 duration: %s", i, d)
        return

    if mode == "render":
        if not MANIM_AVAILABLE:
            raise RuntimeError("Manim not available. Install Manim + LaTeX + ffmpeg to render.")
        MasterclassScene.steps = steps
        MasterclassScene.topic = topic
        MasterclassScene.output_dir = output_dir
        MasterclassScene.temp_dir = audio_dir
        MasterclassScene.combined_audio = combined_audio
        scene = MasterclassScene()
        scene.render()
        logging.info("Render complete. Check Manim's media directory for the final video.")

def main():
    parser = argparse.ArgumentParser(description="PyV — generate educational videos (VS Code friendly)")
    parser.add_argument("--topic", "-t", default="Fundamental Theorem of Arithmetic", help="Lesson topic")
    default_output = os.path.join(os.path.expanduser("~"), "jeevavibeapp-coder", "Edu-Ai", "output")
    default_temp = os.path.join(os.path.expanduser("~"), "jeevavibeapp-coder", "Edu-Ai", "temp creation")
    parser.add_argument("--output", "-o", default=default_output, help="Output folder for audio/video")
    parser.add_argument("--temp", "-T", default=default_temp, help="Temporary assets folder (audio etc.)")
    parser.add_argument("--mode", "-m", choices=["dry-run", "render"], default="dry-run", help="dry-run: generate assets only; render: run Manim to produce video")
    args = parser.parse_args()

    out = Path(args.output)
    temp_dir = Path(args.temp)
    out.mkdir(parents=True, exist_ok=True)
    temp_dir.mkdir(parents=True, exist_ok=True)

    try:
        produce_video(args.topic, output_dir=str(out), mode=args.mode, temp_dir=str(temp_dir))
    except Exception as e:
        logging.exception("Failed to produce video: %s", e)
        sys.exit(1)

    logging.info("Done. Output directory: %s", out.resolve())

if __name__ == "__main__":
    main()
